CREATE DATABASE db_Classificado;

USE db_Classificado;

CREATE TABLE tb_Usuarios(
	Id INT NOT NULL PRIMARY KEY,
	Nome VARCHAR(45) NOT NULL,
	Usuario VARCHAR(45) NOT NULL,
	Senha VARCHAR(100) NOT NULL,
	Pessoa VARCHAR(255) NOT NULL CHECK(Pessoa IN('FIS','JUR')),
	Imagem VARCHAR(100) NOT NULL
);

CREATE TABLE tb_Anuncios(
	Id INT NOT NULL PRIMARY KEY,
	Titulo VARCHAR(255) NOT NULL,
	Descricao VARCHAR(1000) NOT NULL,
	Contato VARCHAR(100),
	Imagem VARCHAR(100),
	Datas DATE,
	FK_Usuario INT NOT NULL
	FOREIGN KEY (FK_Usuario) REFERENCES tb_Usuarios(Id)
);

DROP TABLE tb_Anuncios;